feat: add CreateAuthenticationExecutionFlow
Nerzal/gocloak pull request #327
Opened 2021-12-08 07:49 UTC by weixiao-huang

Thanks for your contribution!
Hi, if there is an issue, that your PR adresses, please link it!

2022-01-03 11:00 UTC, Nerzal commented
Hi, could you please resolve the merge conflicts?

2022-01-03 13:41 UTC, weixiao-huang commented
All conflicts have been resolved

2022-01-03 13:57 UTC, Nerzal commented
Hi again :) 

The code looks good so far. 
Could you please also add a test for that function? :)

2022-01-03 15:36 UTC, weixiao-huang commented
I added tests but I cannot test it in my local machine, so please approve the test ci, thanks

2022-01-10 12:42 UTC, bastianccm requested changes

2022-01-10 12:42 UTC, bastianccm commented on client_test.go
> +	require.True(t, execFlowFound, "Failed to find authentication execution flow")
This should go on block up, before deleting the flow, as the flow removes the execution too. (Simply cut the lines here and move them up to line 6244). Then the test will pass.

2022-01-10 15:27 UTC, bastianccm approved these changes

2022-01-11 12:52 UTC, weixiao-huang commented
Hello, could you please approve the ci to test?

2022-01-31 14:12 UTC, bastianccm commented
Hi @Nerzal can you take a look into this change? Thank you!

2022-02-17 13:28 UTC, Nerzal commented
LGTM thank you for the contribution! 
I'll create a new Release this week, which includes all PRs i merged during the last days

2022-02-17 13:28 UTC, merged